//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZUIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        public string Branch_Code { get; set; }
        public string DSTB_NO { get; set; }
        public string Company_Code { get; set; }
        public string Branch_Name { get; set; }
        public string DSTB_IssuedBy { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
