//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZUIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public string City_code { get; set; }
        public string City_NAME { get; set; }
        public string City_ABBR { get; set; }
        public string Province { get; set; }
        public string COUNTRY_code { get; set; }
    }
}
