//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZUIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company()
        {
            this.Branches = new HashSet<Branch>();
        }
    
        public string Company_Code { get; set; }
        public string Company_name { get; set; }
        public string Company_ABBR { get; set; }
        public string Branch_Code { get; set; }
        public string DSTB_NO { get; set; }
        public string HOD { get; set; }
        public string Address { get; set; }
        public string City_code { get; set; }
        public string REGION { get; set; }
        public string Country_code { get; set; }
        public string POSTAL_CODE { get; set; }
        public string TEL_NO { get; set; }
        public string FAX_NO { get; set; }
        public string EMAIL { get; set; }
        public string Mobile_No { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Branch> Branches { get; set; }
    }
}
