//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZUIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discount_Approval
    {
        public string vendor_code { get; set; }
        public string Customer_code { get; set; }
        public int SNO { get; set; }
        public System.DateTime Valid_Date_from { get; set; }
        public Nullable<System.DateTime> Valid_Date_to { get; set; }
        public string Status { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Customer Customer1 { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
