//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZUIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Purchase_Order = new HashSet<Purchase_Order>();
            this.Purchase_Order1 = new HashSet<Purchase_Order>();
            this.Purchase_Order2 = new HashSet<Purchase_Order>();
            this.Menu_UserReg = new HashSet<Menu_UserReg>();
        }
    
        public int Emp_ID { get; set; }
        public string User_id { get; set; }
        public string Emp_Name { get; set; }
        public string User_name { get; set; }
        public string User_password { get; set; }
        public string Group_id { get; set; }
        public string Authorize_Status { get; set; }
        public string Login_status { get; set; }
        public string User_desc { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Region { get; set; }
        public string Country_code { get; set; }
        public string Postal_Code { get; set; }
        public string Tel_No { get; set; }
        public string Email { get; set; }
        public string Mobile_No { get; set; }
        public string Dept_Code { get; set; }
        public string Branch_No { get; set; }
    
        public virtual Branch_Master Branch_Master { get; set; }
        public virtual Country Country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchase_Order> Purchase_Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchase_Order> Purchase_Order1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchase_Order> Purchase_Order2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Menu_UserReg> Menu_UserReg { get; set; }
    }
}
