//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZUIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_Stock
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item_Stock()
        {
            this.Discount_ApprovalDET = new HashSet<Discount_ApprovalDET>();
            this.SO_ItemDetail = new HashSet<SO_ItemDetail>();
        }
    
        public string Stock_no { get; set; }
        public string Brand_name { get; set; }
        public string Generic_name { get; set; }
        public int Units_PerItem { get; set; }
        public Nullable<decimal> Trade_PriceItem { get; set; }
        public Nullable<decimal> Item_Discount { get; set; }
        public Nullable<decimal> Current_Price { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> PPrice { get; set; }
        public string Manufacturer_Code { get; set; }
        public string Item_Type { get; set; }
        public string Weight_Unit { get; set; }
        public string Item_Desc { get; set; }
        public string BARCODE { get; set; }
        public string Available_status { get; set; }
        public string Location { get; set; }
        public string RefStock_no { get; set; }
        public Nullable<System.DateTime> Record_date { get; set; }
        public string User_id { get; set; }
        public string AltStock_No { get; set; }
        public string GroupNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Discount_ApprovalDET> Discount_ApprovalDET { get; set; }
        public virtual Manufacture Manufacture { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SO_ItemDetail> SO_ItemDetail { get; set; }
    }
}
