//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZUIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Menu()
        {
            this.Menu_User = new HashSet<Menu_User>();
        }
    
        public int Menu_ID { get; set; }
        public string Menu_Title { get; set; }
        public string Abbr { get; set; }
        public string Note { get; set; }
        public string Status { get; set; }
        public Nullable<int> Serial_no { get; set; }
        public string Action { get; set; }
        public string Controller_name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Menu_User> Menu_User { get; set; }
    }
}
