//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZUIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu_User
    {
        public string user_id { get; set; }
        public int Menu_id { get; set; }
        public string AddEditDel { get; set; }
        public string IsFavourite { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public int DisplayOrder { get; set; }
        public string Menu_Group { get; set; }
    
        public virtual Menu Menu { get; set; }
        public virtual Menu_UserReg Menu_UserReg { get; set; }
    }
}
