//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZUIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu_UserReg
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Menu_UserReg()
        {
            this.Menu_User = new HashSet<Menu_User>();
        }
    
        public string User_id { get; set; }
        public string User_Password { get; set; }
        public int Emp_ID { get; set; }
        public Nullable<System.DateTime> Login_Date { get; set; }
        public string IP_Addr { get; set; }
        public string UserType { get; set; }
        public string MenuType { get; set; }
        public string MAC { get; set; }
        public string EnteredBy { get; set; }
        public Nullable<System.DateTime> EnteredOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string Comments { get; set; }
        public Nullable<int> SendLogin_Email { get; set; }
        public string Status { get; set; }
    
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Menu_User> Menu_User { get; set; }
    }
}
