//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZUIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PO_ItemDetail
    {
        public string PO_No { get; set; }
        public string Branch_No { get; set; }
        public string Stock_no { get; set; }
        public Nullable<decimal> POPrice_PerItem { get; set; }
        public int POQty_PerItem { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> CurrExch_rate { get; set; }
        public decimal POMargin_Percentage { get; set; }
        public Nullable<decimal> POExtend_Price { get; set; }
        public string Status { get; set; }
        public Nullable<int> Qty_Pack { get; set; }
    
        public virtual Purchase_Order Purchase_Order { get; set; }
    }
}
