//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZUIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale_Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sale_Invoice()
        {
            this.Sale_InvDET = new HashSet<Sale_InvDET>();
        }
    
        public string Invoice_no { get; set; }
        public string Branch_No { get; set; }
        public System.DateTime Invoice_date { get; set; }
        public string Invoice_type { get; set; }
        public string SO_No { get; set; }
        public Nullable<System.DateTime> SO_Date { get; set; }
        public Nullable<System.DateTime> Delivery_date { get; set; }
        public string Delivery_status { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> Gross_Amount { get; set; }
        public Nullable<decimal> Tax_Percentage { get; set; }
        public Nullable<decimal> Disc_Percentage { get; set; }
        public Nullable<decimal> NET_Amount { get; set; }
        public string Ship_toCustAddr { get; set; }
        public string Ship_toCustCity { get; set; }
        public string Contact_Person { get; set; }
        public string Ship_Via { get; set; }
        public string Shipper_code { get; set; }
        public string Customer_Code { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> Record_date { get; set; }
        public string User_id { get; set; }
    
        public virtual Branch_Master Branch_Master { get; set; }
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale_InvDET> Sale_InvDET { get; set; }
        public virtual Shipper Shipper { get; set; }
        public virtual Sales_order Sales_order { get; set; }
    }
}
