//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZUIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale_InvDET
    {
        public string Invoice_no { get; set; }
        public string Branch_No { get; set; }
        public string Stock_no { get; set; }
        public int SNO { get; set; }
        public Nullable<decimal> SPrice_PerItem { get; set; }
        public Nullable<decimal> SPrice_PerUnit { get; set; }
        public int SQty { get; set; }
        public Nullable<System.DateTime> Expiry_Date { get; set; }
        public string Batch_NO { get; set; }
        public Nullable<decimal> Trade_PriceItem { get; set; }
        public Nullable<decimal> Tax_Percentage { get; set; }
        public Nullable<decimal> Tax_Amount { get; set; }
        public Nullable<decimal> PPrice_Currency { get; set; }
        public Nullable<decimal> Currency_Rate { get; set; }
        public string Sold_Status { get; set; }
        public string Supp_InvNo { get; set; }
        public string Supp_Invno1 { get; set; }
        public Nullable<decimal> TSPrice_PerItem { get; set; }
        public Nullable<decimal> PPrice_PerItem { get; set; }
        public Nullable<int> Serial_no { get; set; }
        public Nullable<System.DateTime> Record_date { get; set; }
        public string User_id { get; set; }
    
        public virtual Sale_Invoice Sale_Invoice { get; set; }
        public virtual Stock_Receipt Stock_Receipt { get; set; }
    }
}
