//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZUIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sales_order()
        {
            this.Sale_Invoice = new HashSet<Sale_Invoice>();
        }
    
        public string SO_No { get; set; }
        public string Branch_No { get; set; }
        public System.DateTime SO_Date { get; set; }
        public string CustPO_No { get; set; }
        public Nullable<System.DateTime> CustPO_Date { get; set; }
        public string PO_No { get; set; }
        public string Customer_Code { get; set; }
        public string Ship_toCustAddr { get; set; }
        public string Ship_toCustCity { get; set; }
        public Nullable<System.DateTime> Delivery_date { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> Gross_Amount { get; set; }
        public Nullable<decimal> Tax_Percentage { get; set; }
        public Nullable<decimal> Disc_Percentage { get; set; }
        public Nullable<decimal> NET_Amount { get; set; }
        public Nullable<System.DateTime> Record_date { get; set; }
        public string User_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale_Invoice> Sale_Invoice { get; set; }
    }
}
