//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZUIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock_Receipt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stock_Receipt()
        {
            this.Sale_InvDET = new HashSet<Sale_InvDET>();
            this.Stock_ReceiptDET = new HashSet<Stock_ReceiptDET>();
        }
    
        public string Supp_Invno { get; set; }
        public string Branch_No { get; set; }
        public string AltSupp_Invno { get; set; }
        public Nullable<System.DateTime> Invoice_Date { get; set; }
        public string vendor_code { get; set; }
        public Nullable<System.DateTime> Received_date { get; set; }
        public Nullable<decimal> Total_Amount { get; set; }
        public string Payment_Type { get; set; }
        public Nullable<decimal> Disc_amount { get; set; }
        public Nullable<decimal> Tax_amount { get; set; }
        public string PO_NO { get; set; }
        public string Status { get; set; }
        public string Received_by { get; set; }
        public string User_id { get; set; }
        public string Currency { get; set; }
        public string Comments { get; set; }
    
        public virtual Purchase_Order Purchase_Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale_InvDET> Sale_InvDET { get; set; }
        public virtual Vendor Vendor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stock_ReceiptDET> Stock_ReceiptDET { get; set; }
    }
}
