//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZUIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock_ReceiptDET
    {
        public string Supp_Invno { get; set; }
        public string Branch_No { get; set; }
        public string Stock_no { get; set; }
        public Nullable<int> Items_Received { get; set; }
        public Nullable<int> PQty_PerItem { get; set; }
        public Nullable<int> Units_PerItem { get; set; }
        public Nullable<decimal> POMargin_Percentage { get; set; }
        public Nullable<decimal> PPrice_PerItem { get; set; }
        public Nullable<decimal> SPrice_PerItem { get; set; }
        public Nullable<decimal> PPrice_Currency { get; set; }
        public Nullable<decimal> Currency_Rate { get; set; }
        public Nullable<decimal> WPrice_PerItem { get; set; }
        public Nullable<System.DateTime> Expiry_Date { get; set; }
        public string Batch_NO { get; set; }
        public Nullable<decimal> Tot_PPriceItem { get; set; }
        public Nullable<decimal> PPrice_PerUnit { get; set; }
        public Nullable<decimal> SPrice_PerUnit { get; set; }
        public Nullable<decimal> Trade_PriceItem { get; set; }
        public Nullable<decimal> Tax_Percentage { get; set; }
        public Nullable<int> Tax_Amount { get; set; }
        public string Received_Status { get; set; }
        public Nullable<int> Items_Available { get; set; }
        public Nullable<System.DateTime> Record_date { get; set; }
        public Nullable<int> Serial_no { get; set; }
        public string User_id { get; set; }
    
        public virtual Stock_Receipt Stock_Receipt { get; set; }
    }
}
