//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZUIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_MerckRPT
    {
        public string Stock_no { get; set; }
        public string Brand_name { get; set; }
        public Nullable<decimal> Trade_PriceItem { get; set; }
        public int Units_PerItem { get; set; }
        public Nullable<int> Items_Available { get; set; }
        public string Manufacturer_Code { get; set; }
        public string GroupNo { get; set; }
        public Nullable<int> SQty { get; set; }
        public Nullable<int> Items_Received { get; set; }
    }
}
