//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZUIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_StockInventory
    {
        public string Stock_no { get; set; }
        public string AltStock_No { get; set; }
        public string Brand_name { get; set; }
        public string Batch_NO { get; set; }
        public int Items_Available { get; set; }
        public string DSTB_NO { get; set; }
        public string Branch_Code { get; set; }
    }
}
