//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZUIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vendor()
        {
            this.Discount_Approval = new HashSet<Discount_Approval>();
            this.Purchase_Order = new HashSet<Purchase_Order>();
            this.Stock_Receipt = new HashSet<Stock_Receipt>();
        }
    
        public string vendor_code { get; set; }
        public string vendor_Title { get; set; }
        public string Name { get; set; }
        public string Contact_Person { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Region { get; set; }
        public string Country_code { get; set; }
        public string Postal_Code { get; set; }
        public string Tel_No { get; set; }
        public string Fax_No { get; set; }
        public string Email { get; set; }
        public string Alt_Address { get; set; }
        public string Alt_City { get; set; }
        public string Alt_Country { get; set; }
        public string Lang_Code { get; set; }
        public Nullable<System.DateTime> Record_date { get; set; }
        public string User_id { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Country Country1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Discount_Approval> Discount_Approval { get; set; }
        public virtual Language Language { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchase_Order> Purchase_Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stock_Receipt> Stock_Receipt { get; set; }
    }
}
